### ISSUE TITLE
Feature Request: filter github activity stream with query

### ISSUE THREAD

**Issue by Shinyaigeek** [sanposhiho/github-activity-tweeter#4]
## Motivation

Hi @sanposhiho !

This is **just a feature request**, so if you don't think this is necessary, please close this issue.
Someone (like me) will want to filter the Github activity stream with a query. In my case, I wanna exclude the activities which are related to my own repositories( shinyaigeek/* ) with `involves:{user} -user{user}` query in GitHub search API.

Do you have any plan to support filtering GitHub activity stream with a query like GitHub search API?

FYI: https://docs.github.com/ja/github/searching-for-information-on-github/searching-on-github/searching-issues-and-pull-requests

**Comment by sanposhiho** [comment]
Looks good. 
wait a minutes

**Comment by sanposhiho** [comment]
Supported in #12

**Comment by Shinyaigeek** [comment]
Thanks! 👍
